TRAIN_FILE = "../input/train.csv"
TEST_FILE = "../input/test.csv"
TRAIN_FOLD = "../input/train_folds.csv"
DEVICE = "cuda"
EPOCH = 100
TRAIN_BATCH_SIZE = 1024
VALID_BATCH_SIZE =64
NUM_WORKERS = 8
LERNING_RATE = 1e-6
